config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: "pages#home"
  get 'video-service',      to: 'pages#video'
  get 'photo-service',      to: 'pages#photo'
  get 'design-service',     to: 'pages#design'
  get 'editorial-service',  to: 'pages#editorial'
  get 'projects',           to: 'pages#projects'
  get 'about',              to: 'pages#about'
  get 'eduardo',            to: 'pages#team_first'
  get 'edgar',              to: 'pages#team_second'
  get 'saletta',            to: 'pages#team_third'

  resources :videos do
    resources :video_images
  end

  get 'videos/:id/video-detail',  to: 'videos#detail', as: 'video-detail'

  resources :photos do
    resources :photo_images
  end

  get 'photos/:id/photo-detail',  to: 'photos#detail', as: 'photo-detail'

  resources :designs do
    resources :design_images
  end

  get 'designs/:id/design-detail',  to: 'designs#detail', as: 'design-detail'

  resources :editorials do
    resources :editorial_images
  end

  get 'editorials/:id/editorial-detail',  to: 'editorials#detail', as: 'editorial-detail'

  get 'contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]

end

app/models/design.rb
class Design < ActiveRecord::Base
  has_many :design_images
  validates :name, :description, presence: true

  scope :featured, -> { where(featured: true) }
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :authenticate_user!, except: :detail

  def index
    @designs = Design.all
  end

  def new
    @design = Design.new
  end

  def create
    @design = Design.new(design_params)

    if @design.save
      redirect_to designs_path, notice: "Your design was created"
    else
      redirect_to new_design_path, notice: "Something went wrong"
    end
  end

  def show
    @design = Design.find(params[:id])
  end

  def detail
    @design = Design.find(params[:id])
  end

  def edit
    @design = Design.find(params[:id])
  end

  def update
    @design = Design.find(params[:id])
    if @design.update(design_params)
      redirect_to designs_path, notice: "El proyecto de diseño ha sido actualizado"
    else
      render "edit"
    end
  end

  def destroy
    @design = Design.find(params[:id])
    @design.destroy
    redirect_to designs_path, notice: "El proyecto de diseño ha sido eliminado"
  end

  private

  def design_params
    params.require(:design).permit(:name, :description, :participants, :featured)
  end

end

app/views/designs/_form.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <%= form_for design, html: {id: 'design_form'} do |f| %>

    <% if @design.errors.any? %>
      <div id="error_explanation" class='bg-danger'>
        <h2>Hay <%= pluralize(@design.errors.count, "error") %> en la forma:</h2>
        <ul>
        <% @design.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_field :name, class: "mdl-textfield__input", type: 'text' %>
        <%= f.label :name, "Nombre", class: 'mdl-textfield__label' %>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_area :description, class: "mdl-textfield__input", type: 'text' %>
        <%= f.label :description, "Descripción", class: 'mdl-textfield__label' %>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_field :participants, class: "mdl-textfield__input", type: 'text' %>
        <%= f.label :participants, "Participantes", class: 'mdl-textfield__label' %>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <span class="mdl-list__item-secondary-action">
       <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="design_featured">
         Featured
         <%= f.check_box :featured, class: 'mdl-checkbox__input' %>
       </label>
     </span>
   </div>


    <div class="mdl-cell mdl-cell--12-col">
      <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
        Guardar
      </button>
    </div>

    <% end %>

  </div>
  <div class="mdl-layout-spacer"></div>
</div>

app/views/designs/detail.html.erb
<div class="mdl-grid mdl-grid-proyect-detail">
  <div class="mdl-cell mdl-cell--12-col mdl-cell-proyect-detail">
    <div class="project-image-detail">
      <div><%= cl_image_tag(@design.design_images.last.file_url, :crop => :fill) %></div>
    </div>
  </div>
</div>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <%= link_to projects_path do %>
      <button class="mdl-button mdl-js-button mdl-button--icon">
         <i class="material-icons">arrow_back</i>
      </button>
    <% end %>
    <h1><%= @design.name %></h1>
  </div>
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--2-col">
    <h3>Colaboradores</h3>
    <span class="mdl-chip">
      <span class="mdl-chip__text"><%= @design.participants %></span>
    </span>
  </div>
</div>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--10-col">
    <p><%= @design.description %></p>
  </div>
</div>

<div class="all-project-images-list">
  <div class="project-list">
    <div class="mdl-grid project-list-grid mdl-grid--no-spacing">
      <% @design.design_images.each do |image| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <div><%= cl_image_tag(image.file_url, :crop => :fill, :width => 180, :height => 180) %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/designs/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <h1>Editar Diseño</h1>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>

<%= render 'form', design: @design %>

app/views/designs/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <div class="mdl-cell mdl-cell--12-col">
      <%= link_to "Nuevo Proyecto de Diseño", new_design_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
    </div>
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp full-width">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric full-width">Nombre</th>
          <th></th>
          <th></th>
          <th>Añadir Fotos</th>
          <th>Editar</th>
          <th>Eliminar</th>
        </tr>
      </thead>
      <tbody>
        <% @designs.each do |design| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= design.name %></td>
            <td></td>
            <td></td>
            <td>
              <%= link_to "Añadir Fotos", design_path(design), class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
            </td>
            <td>
              <%= link_to "Editar", edit_design_path(design), class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
            </td>
            <td>
              <%= link_to "Eliminar", design_path(design), method: :delete,
                  class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent',
                  data: { confirm: 'Estas seguro?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/designs/new.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <h1>Nuevo Proyecto de Diseño</h1>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>

<%= render 'form', design: @design %>

app/views/designs/show.html.erb
<div class="mdl-grid">

  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <h3>Nombre</h3>
    <%= @design.name %>
    <h3>Descripción</h3>
    <%= @design.description %>
    <h3>Participantes</h3>
    <%= @design.participants %>
    <h3>Fotos</h3>
    <% @design.design_images.each do |image| %>
      <div><%= cl_image_tag(image.file_url, :crop => :fill, :width => 180, :height => 180) %></div>
      <div>
        <%= link_to "Eliminar", design_design_image_path(image, @design), method: :delete,
            class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent',
            data: { confirm: 'Estas seguro?'} %>
      </div>
    <% end %>

  </div>
  <div class="mdl-layout-spacer"></div>

  <div class="mdl-layout-spacer"></div>
  <%= render "./design_images/form", { design_image: DesignImage.new, design: @design } %>
  <div class="mdl-layout-spacer"></div>
</div>