config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: "pages#home"
  get 'video-service',      to: 'pages#video'
  get 'photo-service',      to: 'pages#photo'
  get 'design-service',     to: 'pages#design'
  get 'editorial-service',  to: 'pages#editorial'
  get 'projects',           to: 'pages#projects'
  get 'about',              to: 'pages#about'
  get 'eduardo',            to: 'pages#team_first'
  get 'edgar',              to: 'pages#team_second'
  get 'saletta',            to: 'pages#team_third'

  resources :videos do
    resources :video_images
  end

  get 'videos/:id/video-detail',  to: 'videos#detail', as: 'video-detail'

  resources :photos do
    resources :photo_images
  end

  get 'photos/:id/photo-detail',  to: 'photos#detail', as: 'photo-detail'

  resources :designs do
    resources :design_images
  end

  get 'designs/:id/design-detail',  to: 'designs#detail', as: 'design-detail'

  resources :editorials do
    resources :editorial_images
  end

  get 'editorials/:id/editorial-detail',  to: 'editorials#detail', as: 'editorial-detail'

  get 'contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]

end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :video_images
  validates :embed_url, :name, :description, presence: true

  scope :featured, -> { where(featured: true) }
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: :detail

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to videos_path, notice: "Your video was created"
    else
      redirect_to new_video_path, notice: "Something went wrong"
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def detail
    @video = Video.find(params[:id])
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to videos_path, notice: "El video ha sido actualizado"
    else
      render "edit"
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path, notice: "El video ha sido eliminado"
  end

  private

  def video_params
    params.require(:video).permit(:name, :description, :embed_url, :participants, :featured)
  end

end

app/views/videos/_form.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <%= form_for video, html: {id: 'video_form'} do |f| %>

    <% if @video.errors.any? %>
      <div id="error_explanation" class='bg-danger'>
        <h2>Hay <%= pluralize(@video.errors.count, "error") %> en la forma:</h2>
        <ul>
        <% @video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_field :name, class: "mdl-textfield__input", type: 'text' %>
        <%= f.label :name, "Nombre", class: 'mdl-textfield__label' %>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_area :description, class: "mdl-textfield__input", type: 'text' %>
        <%= f.label :description, "Descripción", class: 'mdl-textfield__label' %>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_field :embed_url, class: "mdl-textfield__input", type: 'text' %>
        <%= f.label :embed_url, "Url", class: 'mdl-textfield__label' %>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= f.text_field :participants, class: "mdl-textfield__input", type: 'text' %>
        <%= f.label :participants, "Participantes", class: 'mdl-textfield__label' %>
      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col">
      <span class="mdl-list__item-secondary-action">
       <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="video_featured">
         Featured
         <%= f.check_box :featured, class: 'mdl-checkbox__input' %>
       </label>
     </span>
   </div>

    <div class="mdl-cell mdl-cell--12-col">
      <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
        Guardar
      </button>
    </div>

    <% end %>

  </div>
  <div class="mdl-layout-spacer"></div>
</div>

app/views/videos/detail.html.erb
<div class="mdl-grid mdl-grid-proyect-detail">
  <div class="mdl-cell mdl-cell--12-col mdl-cell-proyect-detail">
    <div class="project-image-detail">
      <div><%= cl_image_tag(@video.video_images.last.file_url, :crop => :fill) %></div>
    </div>
  </div>
</div>
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <%= link_to projects_path do %>
      <button class="mdl-button mdl-js-button mdl-button--icon">
         <i class="material-icons">arrow_back</i>
      </button>
    <% end %>
    <h1><%= @video.name %></h1>
  </div>
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--2-col">
    <h3>Colaboradores</h3>
    <span class="mdl-chip">
      <span class="mdl-chip__text"><%= @video.participants %></span>
    </span>
  </div>
</div>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--10-col">
    <p><%= @video.description %></p>
    <div class="video-project-detail">
    </div>
  </div>
</div>
<br><br><br>

<div class="all-project-images-list">
  <div class="project-list">
    <div class="mdl-grid project-list-grid mdl-grid--no-spacing">
      <% @video.video_images.each do |image| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <div><%= cl_image_tag(image.file_url, :crop => :fill, :width => 180, :height => 180) %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.body.addEventListener('mdl-componentupgraded', function(event) {
     if (event.target.className.split(' ').indexOf('mdl-js-layout') < 0) {
       return
     }

     $('.video-project-detail').append('<iframe class="video-iframe" src="<%= @video.embed_url %>" frameborder="0" allowfullscreen></iframe>')

  })
</script>

app/views/videos/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <h1>Editar Video</h1>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>

<%= render 'form', video: @video %>

app/views/videos/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <div class="mdl-cell mdl-cell--12-col">
      <%= link_to "Nuevo Video", new_video_path, class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
    </div>
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp full-width">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric full-width">Nombre</th>
          <th></th>
          <th></th>
          <th>Editar</th>
          <th>Eliminar</th>
        </tr>
      </thead>
      <tbody>
        <% @videos.each do |video| %>
          <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= video.name %></td>
            <td></td>
            <td></td>
            <td>
              <%= link_to "Añadir Fotos", video_path(video), class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
            </td>
            <td>
              <%= link_to "Editar", edit_video_path(video), class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>
            </td>
            <td>
              <%= link_to "Eliminar", video_path(video), method: :delete,
                  class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent',
                  data: { confirm: 'Estas seguro?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/videos/new.html.erb
<div class="mdl-grid">
  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <h1>Nuevo Video</h1>
  </div>
  <div class="mdl-layout-spacer"></div>
</div>

<%= render 'form', video: @video %>

app/views/videos/show.html.erb
<div class="mdl-grid">

  <div class="mdl-layout-spacer"></div>
  <div class="mdl-cell mdl-cell--4-col">
    <h3>Nombre</h3>
    <%= @video.name %>
    <h3>Descripción</h3>
    <%= @video.description %>
    <h3>Participantes</h3>
    <%= @video.participants %>
    <h3>Fotos</h3>
    <% @video.video_images.each do |image| %>
      <div><%= cl_image_tag(image.file_url, :crop => :fill, :width => 180, :height => 180) %></div>
      <div>
        <%= link_to "Eliminar", video_video_image_path(image, @video), method: :delete,
            class: 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent',
            data: { confirm: 'Estas seguro?'} %>
      </div>
    <% end %>

  </div>
  <div class="mdl-layout-spacer"></div>

  <div class="mdl-layout-spacer"></div>
  <%= render "./video_images/form", { video_image: VideoImage.new, video: @video } %>
  <div class="mdl-layout-spacer"></div>
</div>