config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: "pages#home"
  get 'video-service',      to: 'pages#video'
  get 'photo-service',      to: 'pages#photo'
  get 'design-service',     to: 'pages#design'
  get 'editorial-service',  to: 'pages#editorial'
  get 'projects',           to: 'pages#projects'
  get 'about',              to: 'pages#about'
  get 'eduardo',            to: 'pages#team_first'
  get 'edgar',              to: 'pages#team_second'
  get 'saletta',            to: 'pages#team_third'

  resources :videos do
    resources :video_images
  end

  get 'videos/:id/video-detail',  to: 'videos#detail', as: 'video-detail'

  resources :photos do
    resources :photo_images
  end

  get 'photos/:id/photo-detail',  to: 'photos#detail', as: 'photo-detail'

  resources :designs do
    resources :design_images
  end

  get 'designs/:id/design-detail',  to: 'designs#detail', as: 'design-detail'

  resources :editorials do
    resources :editorial_images
  end

  get 'editorials/:id/editorial-detail',  to: 'editorials#detail', as: 'editorial-detail'

  get 'contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]

end

app/views/project-tabs/_all_projects.html.erb
<div class="all-project-images-list">
  <ul class="project-list">
    <div class="mdl-grid project-list-grid mdl-grid--no-spacing">
      <% designs.each do |project| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <li>
            <%= link_to design_detail_path(project) do %>
              <div id="<%= project.id %>" class="list-project-container">
                <%= cl_image_tag(project.design_images.last.file_url,:crop => :fill, :height => 180, class: 'list-image') %>
                <div class="project-info">
                  <h4><%= project.name %></h4>
                </div>
              </div>
            <% end %>
          </li>
        </div>
      <% end %>
      <% photos.each do |project| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <li>
            <%= link_to photo_detail_path(project) do %>
              <div id="<%= project.id %>" class="list-project-container">
                <%= cl_image_tag(project.photo_images.last.file_url,:crop => :fill, :height => 180, class: 'list-image') %>
                <div class="project-info">
                  <h4><%= project.name %></h4>
                </div>
              </div>
            <% end %>
          </li>
        </div>
      <% end %>
      <% editorials.each do |project| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <li>
            <%= link_to editorial_detail_path(project) do %>
              <div id="<%= project.id %>" class="list-project-container">
                <%= cl_image_tag(project.editorial_images.last.file_url,:crop => :fill, :height => 180, class: 'list-image') %>
                <div class="project-info">
                  <h4><%= project.name %></h4>
                </div>
              </div>
            <% end %>
          </li>
        </div>
      <% end %>
    </div>
  </ul>
</div>

app/views/project-tabs/_design_projects.html.erb
<div class="all-project-images-list">
  <ul class="project-list">
    <div class="mdl-grid project-list-grid mdl-grid--no-spacing">
      <% designs.each do |project| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <li>
            <%= link_to design_detail_path(project) do %>
              <div id="<%= project.id %>" class="list-project-container">
                <%= cl_image_tag(project.design_images.last.file_url,:crop => :fill, :height => 180, class: 'list-image') %>
                <div class="project-info">
                  <h4><%= project.name %></h4>
                </div>
              </div>
            <% end %>
          </li>
        </div>
      <% end %>
    </div>
  </ul>
</div>

app/views/project-tabs/_editorial_projects.html.erb
<div class="all-project-images-list">
  <ul class="project-list">
    <div class="mdl-grid project-list-grid mdl-grid--no-spacing">
      <% editorials.each do |project| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <li>
            <%= link_to editorial_detail_path(project) do %>
              <div id="<%= project.id %>" class="list-project-container">
                <%= cl_image_tag(project.editorial_images.last.file_url,:crop => :fill, :height => 180, class: 'list-image') %>
                <div class="project-info">
                  <h4><%= project.name %></h4>
                </div>
              </div>
            <% end %>
          </li>
        </div>
      <% end %>
    </div>
  </ul>
</div>

app/views/project-tabs/_photo_projects.html.erb
<div class="all-project-images-list">
  <ul class="project-list">
    <div class="mdl-grid project-list-grid mdl-grid--no-spacing">
      <% photos.each do |project| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <li>
            <%= link_to photo_detail_path(project) do %>
              <div id="<%= project.id %>" class="list-project-container">
                <%= cl_image_tag(project.photo_images.last.file_url,:crop => :fill, :height => 180, class: 'list-image') %>
                <div class="project-info">
                  <h4><%= project.name %></h4>
                </div>
              </div>
            <% end %>
          </li>
        </div>
      <% end %>
    </div>
  </ul>
</div>

app/views/project-tabs/_video_projects.html.erb
<div class="all-project-images-list">
  <ul class="project-list">
    <div class="mdl-grid project-list-grid mdl-grid--no-spacing">
      <% videos.each do |project| %>
        <div class="mdl-cell mdl-cell--4-col list-image">
          <li>
            <%= link_to video_detail_path(project) do %>
              <div id="<%= project.id %>" class="list-project-container">
                <%= cl_image_tag(project.video_images.last.file_url,:crop => :fill, :height => 180, class: 'list-image') %>
                <div class="project-info">
                  <h4><%= project.name %></h4>
                </div>
              </div>
            <% end %>
          </li>
        </div>
      <% end %>
    </div>
  </ul>
</div>