config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root to: "pages#home"
  get 'video-service',      to: 'pages#video'
  get 'photo-service',      to: 'pages#photo'
  get 'design-service',     to: 'pages#design'
  get 'editorial-service',  to: 'pages#editorial'
  get 'projects',           to: 'pages#projects'
  get 'about',              to: 'pages#about'
  get 'eduardo',            to: 'pages#team_first'
  get 'edgar',              to: 'pages#team_second'
  get 'saletta',            to: 'pages#team_third'

  resources :videos do
    resources :video_images
  end

  get 'videos/:id/video-detail',  to: 'videos#detail', as: 'video-detail'

  resources :photos do
    resources :photo_images
  end

  get 'photos/:id/photo-detail',  to: 'photos#detail', as: 'photo-detail'

  resources :designs do
    resources :design_images
  end

  get 'designs/:id/design-detail',  to: 'designs#detail', as: 'design-detail'

  resources :editorials do
    resources :editorial_images
  end

  get 'editorials/:id/editorial-detail',  to: 'editorials#detail', as: 'editorial-detail'

  get 'contacts',     to: 'contacts#new'
  resources "contacts", only: [:new, :create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nuail</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
  <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
  <body>

    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

      <div class="nuail-header mdl-layout__header mdl-layout__header--waterfall">
        <div class="mdl-layout__header-row">
          <%= link_to root_path do %>
            <span class="nuail-title mdl-layout-title">
              <%= image_tag 'nuail-3.png', class: 'nuail-logo-image-main' %>
            </span>
          <% end %>
          <!-- Add spacer, to align navigation to the right in desktop -->
          <div class="nuail-header-spacer mdl-layout-spacer"></div>
          <!-- Navigation -->
          <div class="nuail-navigation-container">
            <nav class="nuail-navigation mdl-navigation">
              <% if current_user %>
                <%= link_to "VIDEOS", videos_path, class: "mdl-navigation__link" %>
                <%= link_to "NU-BUNDLE", editorials_path, class: "mdl-navigation__link" %>
                <%= link_to "PHOTOS", photos_path, class: "mdl-navigation__link" %>
                <%= link_to "DESIGNS", designs_path, class: "mdl-navigation__link" %>
                <%= link_to "CHANGE PASSWORD", edit_user_registration_path, class: "mdl-navigation__link" %>
                <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, class: "mdl-navigation__link" %>
              <% else %>
                <button class="mdl-navigation__link mdl-button mdl-js-button" id="servicios-navbar">
                  Servicios
                </button>
                <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect" for="servicios-navbar">
                  <%= link_to "VIDEOS", video_service_path, class: "mdl-menu__item" %>
                  <%= link_to "FOTOGRAFÍA", photo_service_path, class: "mdl-menu__item" %>
                  <%= link_to "DISEÑO", design_service_path, class: "mdl-menu__item" %>
                  <%= link_to "NU-BUNDLE", editorial_service_path, class: "mdl-menu__item" %>
                </ul>
                <%= link_to "PROYECTOS", projects_path, class: "mdl-navigation__link mdl-typography--text-uppercase" %>
                <%= link_to "NOSOTROS", about_path, class: "mdl-navigation__link mdl-typography--text-uppercase" %>
                <%= link_to "CONTACTO", new_contact_path, class: "mdl-navigation__link mdl-typography--text-uppercase" %>
              <% end %>
            </nav>
          </div>
          <span class="nuail-mobile-title mdl-layout-title">
            <%= image_tag 'nuail-2.png', class: 'nuail-logo-image' %>
          </span>

        </div>
      </div>

      <div class="nuail-drawer mdl-layout__drawer">
        <span class="mdl-layout-title">
          <%= image_tag 'nuail-3.png', class: 'nuail-logo-image' %>
        </span>
        <nav class="mdl-navigation">
          <%= link_to "VIDEOS", video_service_path, class: "mdl-navigation__link" %>
          <%= link_to "FOTOGRAFÍA", photo_service_path, class: "mdl-navigation__link" %>
          <%= link_to "DISEÑO", design_service_path, class: "mdl-navigation__link" %>
          <%= link_to "NU-BUNDLE", editorial_service_path, class: "mdl-navigation__link" %>
          <%= link_to "PROYECTOS", projects_path, class: "mdl-navigation__link" %>
          <%= link_to "NOSOTROS", about_path, class: "mdl-navigation__link" %>
          <%= link_to "CONTACTO", new_contact_path, class: "mdl-navigation__link" %>
        </nav>
      </div>
      <%= render partial: "shared/flash_messages", flash: flash %>

      <div class="nuail-content mdl-layout__content">
        <a name="top"></a>
        <%= yield %>
      </div>
    </div>
    <footer class="nuail-footer mdl-mega-footer">
      <div class="mdl-mega-footer--top-section">
        <div class="mdl-mega-footer--left-section">
          <%= link_to image_tag('facebook.png'), "https://www.facebook.com/NUAILMEDIAMX/", class: 'footer-social-icon', target: "_blank" %>
          &nbsp;
          <%= image_tag 'twitter.png', width: 45, height: 45 %>
          &nbsp;
          <%= link_to image_tag('instagram.png'), "https://www.instagram.com/nuailmedia/?hl=en", class: 'footer-social-icon', target: "_blank" %>
        </div>
        <div class="mdl-mega-footer--right-section">
          <a class="mdl-typography--font-light" href="#top">
            Regresar al principio
            <i class="material-icons">expand_less</i>
          </a>
        </div>
      </div>

      <div class="mdl-mega-footer--middle-section">
        <p class="mdl-typography--font-light">© Nuail Media 2017</p>
        <p class="mdl-typography--font-light">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
      </div>

      <div class="mdl-mega-footer--bottom-section">
        <%= link_to "Admin", user_session_path, class: 'nuail-link nuail-admin-link mdl-typography--font-light' %>
      </div>
    </footer>
  </body>
</html>